name: CI Pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.provide_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build and check
        uses: christopherfrieler/gradle-wrapper-action@v0.6.0
        with:
          arguments: |
            check assemble generatePomFileForMavenPublication kotlinSourcesJar
            versionFile
          artifacts: |
            core-build kraftsql/build/publications/maven/pom-default.xml kraftsql/build/libs/kraftsql-*.jar
            testing-build kraftsql-testing/build/publications/maven/pom-default.xml kraftsql/build/libs/kraftsql-*.jar
            examples-test-report examples/build/reports/tests/test/**/*
      - id: provide_version
        run: echo "version=$(cat build/version.txt)" >> "$GITHUB_OUTPUT"
